### ISSUE TITLE
Research Question

### ISSUE THREAD

**Issue by hanrach** [STAT547-UBC-2019-20/group_2_youtube#11]
Hey @mnybe1 

I think we are almost done! Plan of action sounds good. 
For the research question maybe we can do this one:
- What is the relationship between video category, number of views it recieves, likes/dislikes and comment count?

We can have some sub questions like

- Does the number of comment counts on Youtube videos correlate with the number of likes or dislikes on a video? 
- What trends exist between comment count and video likes/dislikes?

Do you think we need to add anything else for data description?

**Comment by mnybe1** [comment]
Ok I think we're good! Just fixed up the research question section and otherwise I think data description should be fine! Do you know if we need to edit the markdown file so that it knits without showing R code, or best to leave in for now?

**Comment by hanrach** [comment]
I think it's fine to show the R code, maybe that's what they are looking for too. 
I got confused about the instruction that says
"You must include the URL of your public project’s repo in the README.md file of your milestone1 repo, so we know where to find it."

Do we have to create a separate repo called `milestone1'?

**Comment by mnybe1** [comment]
I don't think we create a separate repo. Just added what I think is the project repo URL to the read me.

**Comment by hanrach** [comment]
Ok, cool. I created a release a tag, I think we are done?

**Comment by mnybe1** [comment]
Perfect, thanks!

**Comment by hanrach** [comment]
I'm trying to submit the url on canvas, it seems like it's locked. do you have this problem too?

**Comment by mnybe1** [comment]
oh yeah strange, me too!
