### ISSUE TITLE
milestone 3  feedback

### ISSUE THREAD

**Issue by yuliaUU** [STAT547-UBC-2019-20/group_2_youtube#32]
Excellent work, all is great but I found some minor issue in the usage section:
- only 3 libraries were specified: but you did use package `here` too and maybe even more? double-check that you list all the libraries used

**Comment by yuliaUU** [comment]
sorry ! means milestone 2!!

**Comment by hanrach** [comment]
![image](https://user-images.githubusercontent.com/16642569/76592209-e73fe480-64af-11ea-95f9-5a2308bf89c5.png)
Hi Yulia, do you mean the library specifications in the readme? I think we listed 5 libraries that we've used.

**Comment by yuliaUU** [comment]
but not in the release you provided on canvas . see the [link](https://github.com/STAT547-UBC-2019-20/group_2_youtube/releases/tag/2.0) you provided:
![image](https://user-images.githubusercontent.com/54612866/76592388-74833900-64b0-11ea-9813-7fb5d7da5f30.png)

**Comment by hanrach** [comment]
Oh, okay.

**Comment by yuliaUU** [comment]
i can see now that you did work on that, so will give you those points back:)

**Comment by hanrach** [comment]
I'll make sure to upload the latest release next time :)

**Comment by yuliaUU** [comment]
sounds good:)
